# токен бота
bot.token: ""

# что отображать в статусе
bot.activity: ""

# id stuff-сервера
bot.stuffServerId: ""

# если включить, то бот зарегистрирует все команды на 'bot.stuffServerId' сервере
# в проде не рекомендую это включать
bot.developmentEnvironment: false

# а это массив с идентификаторами голосовых каналов, где бот должен быть доступен
# оставить пустым (то есть `bot.allowedVoices: []`), если ограничение не нужно
bot.allowedVoices:
  - "764589464982388776"
  - "932025313637064724"
